Repository jaibhedia/VoteChain, pull requests merged in 2024-05, with the labels that each got.

#16 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, 1-POINT, GSSOC'24

#29 Add .gitignore File
  .gitignore
Labels: enhancement, good first issue, 1-POINT, GSSOC'24

#30 Create greetings.yaml #26
  .github/workflows/greetings.yaml
Labels: enhancement, Level 1, GSSOC'24

#49 Update README.md
  README.md
Labels: documentation, good first issue, 1-POINT, GSSOC'24

#55 [Feature] : Implement New Ui for login Page
  src/css/registration_from.css
  src/js/script.js
  src/views/registration-form.ejs
Labels: enhancement, good first issue, Level 1, GSSOC'24

#54 Added pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, good first issue, 1-POINT, GSSOC'24
